# Generated by Django 6.0.3 on 2026-05-10 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_person_lineage_group_crawl_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisambiguationKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
                ('weight', models.CharField(choices=[('hard', 'Hard (strong include)'), ('soft', 'Soft (supportive)'), ('uncertain', 'Uncertain (verify)')], default='soft', max_length=10)),
                ('applies_to_groups', models.JSONField(default=list, help_text='List of LineageGroup codes; empty = all groups')),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['weight', 'term'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier used by source modules', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('web', 'Web search'), ('archive', 'Internet Archive'), ('youtube', 'YouTube'), ('google_books', 'Google Books'), ('open_library', 'OpenLibrary'), ('podcast', 'Podcast directory'), ('official_site', 'Official site')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('applies_to_groups', models.JSONField(default=list, help_text='List of LineageGroup codes; empty = all groups')),
                ('max_per_term', models.PositiveIntegerField(default=10)),
                ('rate_limit_seconds', models.FloatField(default=2.0)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Source-specific config (URLs, params)')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A_BABUJI', 'A — Babuji + direct disciples'), ('B_LALAJI_DIRECT', "B — Lalaji's direct disciples"), ('C_LINEAGE', "C — Lalaji's predecessor lineage")], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial (some sources failed)'), ('failed', 'Failed')], default='running', max_length=10)),
                ('triggered_by', models.CharField(default='manual', help_text='cron | manual | <user>', max_length=50)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['group', '-started_at'], name='crawler_cra_group_e80454_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidatePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('suggested_group', models.CharField(blank=True, choices=[('A_BABUJI', 'A — Babuji + direct disciples'), ('B_LALAJI_DIRECT', "B — Lalaji's direct disciples"), ('C_LINEAGE', "C — Lalaji's predecessor lineage")], max_length=20)),
                ('evidence_url', models.URLField(blank=True, max_length=2000)),
                ('evidence_text', models.TextField(blank=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_candidates', to='content.person')),
            ],
            options={
                'ordering': ['-occurrence_count', 'name'],
                'unique_together': {('name', 'suggested_group')},
            },
        ),
        migrations.CreateModel(
            name='PersonAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, help_text='ISO code or freeform (en, hi, ta, ...)', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='content.person')),
            ],
            options={
                'verbose_name_plural': 'person aliases',
                'ordering': ['person', 'alias'],
                'unique_together': {('person', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A_BABUJI', 'A — Babuji + direct disciples'), ('B_LALAJI_DIRECT', "B — Lalaji's direct disciples"), ('C_LINEAGE', "C — Lalaji's predecessor lineage")], max_length=20)),
                ('url', models.URLField(max_length=2000)),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('snippet', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('book', 'Book'), ('article', 'Article'), ('pdf', 'PDF'), ('image', 'Image'), ('other', 'Other')], default='article', max_length=20)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('matched_aliases', models.JSONField(blank=True, default=list)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='Extra categorization tags')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawler_discoveries', to='content.language')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawler_discoveries', to='content.person')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='crawler.crawlrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discoveries', to='crawler.source')),
            ],
            options={
                'verbose_name_plural': 'discoveries',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['run', 'person'], name='crawler_dis_run_id_6adaee_idx'), models.Index(fields=['group', '-discovered_at'], name='crawler_dis_group_95b36c_idx'), models.Index(fields=['publish_date'], name='crawler_dis_publish_ad11d1_idx'), models.Index(fields=['status'], name='crawler_dis_status_564850_idx')],
            },
        ),
    ]
