# Generated by Django 5.2.10 on 2026-03-21 20:28

import django.db.models.deletion
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('master', 'Master'), ('disciple', 'Disciple'), ('researcher', 'Researcher'), ('other', 'Other')], default='master', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='content.category')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='content.language')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='content.person')),
            ],
            options={
                'ordering': ['title'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('source', models.CharField(choices=[('google', 'Google'), ('youtube', 'YouTube'), ('archive', 'Archive'), ('other', 'Other')], max_length=50)),
                ('content_type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('image', 'Image'), ('article', 'Article')], max_length=10)),
                ('snippet', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('search_term_used', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('person_mentioned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discoveries', to='content.person')),
            ],
            options={
                'verbose_name_plural': 'discoveries',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerSearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('last_searched', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_terms', to='content.person')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content_type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('image', 'Image'), ('link', 'Link')], max_length=10)),
                ('file', models.FileField(blank=True, upload_to='content/')),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('external_url', models.URLField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('chapter_number', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='content.category')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='content.collection')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='content.language')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='content.person')),
                ('tags', models.ManyToManyField(blank=True, related_name='content_items', to='content.tag')),
            ],
            options={
                'ordering': ['collection', 'chapter_number', '-created_at'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
