# Generated by Django 5.2.12 on 2026-03-21 18:48

import django.db.models.deletion
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('audio', 'Audio'), ('pdf', 'PDF')], default='audio', max_length=10)),
                ('drive_file_id', models.CharField(help_text='Google Drive file ID', max_length=255)),
                ('drive_url', models.URLField(blank=True, help_text='Direct Google Drive URL (auto-generated from file ID if blank)', max_length=500)),
                ('file_hash', models.CharField(blank=True, help_text='MD5 hash of the file for change detection', max_length=128)),
                ('last_modified_remote', models.DateTimeField(blank=True, help_text='Last modified timestamp from Google Drive', null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration in seconds (audio only)', null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='content.author')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='content.subject')),
                ('tags', models.ManyToManyField(blank=True, related_name='content_items', to='content.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
