# Generated by Django 5.2.10 on 2026-03-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='source',
            field=models.CharField(choices=[('google', 'Google'), ('duckduckgo', 'DuckDuckGo'), ('youtube', 'YouTube'), ('archive', 'Archive'), ('other', 'Other')], max_length=50),
        ),
    ]
